package com.mycom.api;

import java.text.MessageFormat;
import java.util.Date;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * Controller class that exposes APIs for greeting users.
 *
 * @author Chandra Veerapaneni
 */
@RestController
@RequestMapping("/greetings")
public class GreetingApi {
    /** Template message for greeting. */
    private static final String GREETING_TEMPLATE = "Hello {0}.";
    private static final String GREETING_WITH_TIME_TEMPLATE = "Hello {0}. Current time is {1}.";

    /**
     * This method is used to greet the user.
     *
     * @return Greeting message generated by the system.
     */
    @GetMapping("/greet")
    public ResponseEntity<String> greet(@RequestParam(value = "name", defaultValue = "World") final String name) {
        return ResponseEntity.ok(MessageFormat.format(GreetingApi.GREETING_TEMPLATE, name));
    }

    /**
     * This method is used to greet the user.
     *
     * @return Greeting message generated by the system.
     */
    @GetMapping("/greetWithTime")
    public ResponseEntity<String> greetWithTime(
            @RequestParam(value = "name", defaultValue = "World") final String name) {
        return ResponseEntity.ok(MessageFormat.format(GreetingApi.GREETING_WITH_TIME_TEMPLATE, name, new Date()));
    }
}
